version: "2"

services:
  workstation-0:
    image: registry.training.local/workstation-0:${IMAGE_VERSION}
    network_mode: bridge
    environment:
      - "SERVICE_NAME=firek"
    ports:
      - "4567"
